config/routes.rb
Project4::Application.routes.draw do
  root 'photos#index'

  get 'photos' => 'photos#index', :as => :photos
  get 'photos/new' => 'photos#new', :as => :new_photo
  post 'photos' => 'photos#create'
  post '/' => 'photos#create'
  get 'photos/:id' => 'photos#show', :as => :photo
  delete 'photos/:id' => 'photos#destroy'
  get 'photos/like/:id' => 'photos#like', :as => :like_photo
  get 'photos/colors/:color' => 'photos#color_search', :as => :c_search
  
  resources :users
  get 'users/likes/:id' => 'users#show_likes', :as => :show_likes

  get 'auths/new' => 'auths#new', :as => :new_auth
  post 'auths' => 'auths#create'
  delete 'auths' => 'auths#destroy'

  resources :favorites

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
require 'open-uri'
class Photo < ActiveRecord::Base
	belongs_to :user
  has_colors
  has_many :photo_colors
	#has_many :favorites
	#has_many :users, through: :favorites
	has_many :likes

	has_attached_file :image, 
		:styles => { 
			:original => '800x800',
			:medium => "500x500>", 
			:thumb => "100x100>" }, 
			:default_url => "/images/:style/missing.png"
  
  #verifies that image content type has a image/something (png, jpeg, whatever).
  # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  do_not_validate_attachment_file_type :image, :content_type => /\Aimage\/.*\Z/

  def image_url=(url)
  	self.image = open(url)
  end
end

app/models/photo_color.rb
class PhotoColor < ActiveRecord::Base
  belongs_to :photo
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
	has_many :photos
	#has_many :favorites
	# has_many :photos, through: :favorites
	has_many :likes
	has_many :liked_photos, through: :likes, source: :photo


	attr_accessor :password

	def authenticated? pwd
		self.hashed_password == BCrypt::Engine.hash_secret(pwd, self.salt)
	end

	before_save :hash_stuff

	private
	def hash_stuff
		self.salt = BCrypt::Engine.generate_salt
	  	self.hashed_password = BCrypt::Engine.hash_secret(self.password, self.salt)
	  	self.password = nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
  	if session[:user_id]
  		@current_user ||= User.find(session[:user_id])
  	end
  end
end

app/controllers/auths_controller.rb
class AuthsController < ApplicationController
	def new
		if current_user
			redirect_to :root
		else
			@user = User.new
			redirect_to :root
		end
	end

	def create
		user = User.find_by(email: params[:user][:email]) #:user represents the @user from the 'new' action.  It is saying, take the params from the @user form, then its username.
		if user.authenticated?(params[:user][:password])
			session[:user_id] = user.id
			redirect_to :root
		else
			render action "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to :root
	end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

	def index
		@favorites = Favorite.where(user_id: current_user.id)
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  #Enable cross-site scripting *************************************************************
  skip_before_filter :verify_authenticity_token
  before_filter :cors_preflight_check
  after_filter :cors_set_access_control_headers

  # For all responses in this controller, return the CORS access control headers.
  def cors_set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST,GET,OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"
  end

  # If this is a preflight OPTIONS request, then short-circuit the
  # request, return only the necessary headers and return an empty
  # text/plain.

  def cors_preflight_check
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST,GET,OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With'
    headers['Access-Control-Max-Age'] = '1728000'
  end
  # *******************************************************************************************
  def index
  	@photos = Photo.all
    @colors = ["660000", "990000", "cc0000", "cc3333", "ea4c88",
    "993399", "663399", "333399", "0066cc", "0099cc", "66cccc",
    "77cc33", "669900", "336600", "666600", "999900", "cccc33",
    "ffff00", "ffcc33", "ff9900", "ff6600", "cc6633", "996633",
    "663300", "000000", "999999", "cccccc", "ffffff"]
    @user = User.new
  end

  def new
  	@photo = Photo.new
  end

  def create
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST,GET,OPTIONS'
    headers['Access-Control-Max-Age'] = "1728000"

    
    puts params.inspect
    if params[:url]
      # response = HTTParty.get params[:url]
      @photo = Photo.new(url: params[:url], user_id: current_user.id)
      @photo.image_url = params[:url]
      #binding.pry
    else
  		@photo = Photo.new(photo_params)
    end

    # if current_user
    #   @photo.user_id = current_user.id
    # end
    
    puts("hello world")
		if @photo.save
			#redirect_to photo_path(@photo)
			redirect_to photos_path
		else
			render action: 'new'
		end
  end

  def show
  	@photo = Photo.find(params[:id])
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy
    redirect_to :root
  end

  def like
    @like = Like.new
    @user = current_user
    @photo = Photo.find(params[:id])
    @like.user_id = @user.id
    @like.photo_id = @photo.id
    @like.save
    redirect_to :root
    # user = current_user
    # photo = Photo.find(params[:id])
    # user.like!(photo)
    # redirect_to :root
  end

  def color_search
    @photos = Photo.matching_color(params[:color])
    # render color_search partial
  end

	private
	def photo_params
		params.require(:photo).permit(:url, :user_id, :user, :image, :authenticity_token)
	end
end

app/controllers/socializations_controller.rb
class SocializationsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params.require(:user).permit(:email, :password))
		if @user.save
			redirect_to :root
		else
			render action: "index"
		end
	end

  def show
    @user = User.find(params[:id])
    @photos = @user.photos.all
  end

  def show_likes
    @user = User.find(params[:id])
    @likes = @user.likes.includes(:photo)
    @photos = @user.photos.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auths_helper.rb
module AuthsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/socializations_helper.rb
module SocializationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/auths/create.html.erb
<h1>Auths#create</h1>
<p>Find me in app/views/auths/create.html.erb</p>

app/views/auths/destroy.html.erb
<h1>Auths#destroy</h1>
<p>Find me in app/views/auths/destroy.html.erb</p>

app/views/auths/new.html.erb
<h1>Login</h1>

<%= form_for @user, {url: "/auths"} do |u| %>

	<%= u.text_field :email, :placeholder => "Enter Email" %>
	<%= u.password_field :password, :placeholder => "Enter Password" %>
	<%= u.submit "Log In" %>

<% end %>

app/views/favorites/index.html.erb
<ul class="photo-grid">
    <% @photos.each do |photo| %>
        <li>
            <%#= photo.filename %>
            <%= link_to photo_path(photo) do %> <!-- opening for you a tag -->
                <%= image_tag photo.image.url(:medium) %>
                <div><h3>Add</h3></div>
            <% end %> <!-- close of a tag -->
        </li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Grappple" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "main", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/photos/_loginform.html.erb
<h1>Login</h1>

<%= form_for @user, {url: "/auths"} do |u| %>

	<%= u.text_field :email, :placeholder => "Enter Email" %>
	<%= u.password_field :password, :placeholder => "Enter Password" %>
	<%= u.submit "Log In" %>

<% end %>

app/views/photos/_signupform.html.erb
<h1>Sign up!</h1>

<%= form_for @user do |user| %>

	<%= user.text_field :email, :placeholder => "Enter Email" %>
	<%= user.password_field :password, :placeholder => "Enter Password" %>
	<%= user.submit %>

<% end %>

app/views/photos/color_search.html.erb
<!-- NAVBAR -->
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to "Grappple", photos_url %>
      </h1>
    </li>
  </ul>

  <section class="top-bar-section">
  <!-- Right Nav -->
   <a onclick="alert('To install the Snag It button, drag it to your bookmarks toolbar!');return false;" href="javascript:void((function(d){var%20e=d.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://grappple.herokuapp.com/javascripts/snagger.js?r='+Math.random()*99999999);d.body.appendChild(e)})(document));" class="button">Snap It</a> 

    <ul class="right">
      <% if current_user %>
        <li><%= link_to "Back", photos_path %></li>
        <li class="has-dropdown">
          <a href="<%= photos_path %>", class="dashboard">Hello, <%= current_user.email == nil ? current_user.email : current_user.email %></a>
          <ul class="dropdown">
            <li><%= link_to "Log Out", {:controller => 'auths', :action => 'destroy'}, {:method => :delete} %></li>
            <li><%= link_to "My Profile", user_path(current_user) %></li>   
          </ul>
        </li>
    </ul>
      <% else %>
        <ul class="right">
          <li><%= link_to "Back", photos_path %></li>
        </ul>
      <% end %>
  </section>
</nav>

<!-- PHOTO GRID: DUAL COLUMN -->
<ul class="photo-grid">
  <% @photos.each do |photo| %>
    <li>
      </div>
          <%= link_to photo_path(photo) do %>
              <%= image_tag photo.image.url(:medium) %>
              <div></div>
          <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/photos/destroy.html.erb
<h1>Photos#destroy</h1>
<p>Find me in app/views/photos/destroy.html.erb</p>

app/views/photos/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grappple</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

<body>
  <!-- NAVBAR -->
  <nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1>
          <%= link_to "Grappple", photos_url %>
        </h1>
      </li>
    </ul>

    <section class="top-bar-section">
    <!-- Right Nav Section -->
     <a onclick="alert('To install the Snag It button, drag it to your bookmarks toolbar!');return false;" href="javascript:void((function(d){var%20e=d.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://grappple.herokuapp.com/javascripts/snagger.js?r='+Math.random()*99999999);d.body.appendChild(e)})(document));" class="button">Snap It</a> 

      <ul class="right">
        <% if current_user %>
          <li><%= link_to "Color Search", "#color-palette" %></li>
          <li class="has-dropdown">
            <a href="<%= photos_path %>", class="dashboard">Hello, <%= current_user.email == nil ? current_user.email : current_user.email%></a>
            <ul class="dropdown">
              <li><%= link_to "Log Out", {:controller => 'auths', :action => 'destroy'}, {:method => :delete} %></li>
              <li><%= link_to "My Profile", user_path(current_user) %></li>   
            </ul>
          </li>
      </ul>
        <% else %>
          <ul class="right">
            <li><%= link_to "Color Search", "#color-palette" %></li>
            <li data-reveal-id="loginModal"><%= link_to "Log In", {:controller => 'auths', :action => 'new'} %></li>
            <li data-reveal-id="signupModal"><%= link_to "Sign Up", {:controller => 'users', :action => 'new'} %></li>
          </ul>
        <% end %>
    </section>
  </nav>
  
  <!-- COLOR SEARCH PALETTE -->
  <div id="color-palette" class="modalDialog">
    <div>
      <a href="#close" title="Close" class="close">X</a>
      <div class="overlay">
        <% @colors.each do |color| %>
          <%= link_to c_search_path(color: color) do %>
            <div style="background-color: #<%= color %>;" class="box"></div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
 

  <!-- LOGIN MODAL -->
  <div id="loginModal" class="reveal-modal" data-reveal>
    <%= render :partial =>'loginform', :controller => 'auths', :action => 'new' %>
    <a class="close-reveal-modal">&#215;</a>
  </div>

  <!-- SIGNUP MODAL -->
  <div id="signupModal" class="reveal-modal" data-reveal>
    <%= render :partial =>'signupform', :controller => 'users', :action => 'new' %>
    <a class="close-reveal-modal">&#215;</a>
  </div>


  <!-- PHOTO GRID CONTAINER -->
  <div class="main row">
    <div class="large-12 column no-pad"> 
      <div class="giftwrapper small-12 column no-pad"> 
        <div>
          <% @photos.each do |photo| %>
            <div class="gif-box large-2 medium-3 small-4 columns no-pad"
                  style="background-image: url(<%= photo.image.url(:medium) %>)"
                  >
            <span class="roll" ></span>
            </div>
          <% end %>                                                         
        </div>  
      </div>
    </div>
  </div>

</body>

app/views/photos/new.html.erb
<h1>New Photo:</h1>

<div>
	<%= form_for @photo do |p| %>
		<div>
			<%= p.label :image, "Image" %>
			<%= p.file_field :image %>
		</div>

		<div>
			<%= p.submit "Upload Photo" %>
		</div>
	<% end %>
</div>
<br />
<br />
<br />
<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<!-- NAVBAR -->
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1>
        <%= link_to "Grappple", photos_url %>
      </h1>
    </li>
  </ul>

  <section class="top-bar-section">
  <!-- Right Nav Section -->
  	<a onclick="alert('To install the Snag It button, drag it to your bookmarks toolbar!');return false;" href="javascript:void((function(d){var%20e=d.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://grappple.herokuapp.com/javascripts/snagger.js?r='+Math.random()*99999999);d.body.appendChild(e)})(document));" class="button">Snap It</a>  
    <ul class="right">
    	<% if current_user %>
	      <li><%= link_to "Back", photos_path %></li>
	      <li class="has-dropdown">
	        <a href="<%= photos_path %>", class="dashboard">Hello, <%= current_user.email == nil ? current_user.email : current_user.email%></a>
	        <ul class="dropdown">
	          <li> <%= link_to "Log Out", {:controller => 'auths', :action => 'destroy'}, {:method => :delete}  %> </li>
	          <li> <%= link_to "My Profile", user_path(current_user) %> </li>   
	        </ul>
	      </li>
	  </ul>
    	<% else %>
	      <ul class="right">
	        <li><%= link_to "Back", photos_path %></li>
	      </ul>
    	<% end %>
  </section>
</nav>

<!-- PHOTO SUMMARY -->
<div class="show">
	<h1>Photo Summary</h1>
		<div>
			<%= image_tag @photo.image.url(:medium) %>
		</div>
		<%= link_to "Delete", photo_path, method: "delete" %><br />
		<%= link_to "Back", photos_path %><br />
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<%= link_to "New", {:controller => 'users', :action => 'new'} %>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= form_for @user do |user| %>

	<%= user.text_field :email, :placeholder => "Enter Email" %>
	<%= user.password_field :password, :placeholder => "Enter Password" %>
	<%= user.submit %>

<% end %>

app/views/users/show.html.erb
<h1>Profile page</h1>
<h3>Hi, <%= @user.email %></h3> 

<ul class="photo-grid">
    <% @photos.each do |photo| %>
        <li>
            <%#= photo.filename %>
            <%= link_to photo_path(photo) do %> <!-- opening for you a tag -->
                <%= image_tag photo.image.url(:medium) %>
                <div><h3>Add</h3></div>
            <% end %> <!-- close of a tag -->
        </li>
    <% end %>
</ul>

app/views/users/show_likes.html.erb
<%= link_to "My Adds", {controller: 'users', action: 'show'}%><br>
<%= link_to "My Likes", {controller: 'users', action: 'show_likes'}%>

<div><%= image_tag @user.liked_photos.first.image.url(:original), class: "most_recent_like" %></div>

<ul class="photo-grid">
    <% @likes.each do |like| %>
        <li>
            <%#= photo.filename %>
            <%= link_to photo_path(like.photo_id) do %> <!-- opening for you a tag -->
                <%= image_tag like.photo.image.url(:medium) %>
            <% end %> <!-- close of a tag -->
        </li>
    <% end %>
</ul>